routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return view('auth.login');
});
Route::get('/percobaan/{nilai1}/test/{nilai2}', 'percobaanController@testing');

Route::get('/customer', function() {
    return view('testcustomer');
})->name('testcustomer');

Route::resource("users", "UserController");

Route::resource('orders', 'OrderController');

Route::get('/books/trash', 'BookController@trash')->name('books.trash');
Route::post('/books/{book}/restore', 'BookController@restore')->name('books.restore');
Route::delete('/books/{id}/delete-permanent', 'BookController@deletePermanent')->name('books.delete-permanent');
Route::resource('books', 'BookController');

Route::get('/ajax/categories/search', 'CategoryController@ajaxSearch');
Route::get('/categories/trash', 'CategoryController@trash')->name('categories.trash');
Route::get('/categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');
Route::delete('/categories/{category}/delete-permanent','CategoryController@deletePermanent')->name('categories.deletepermanent');
Route::resource('categories', 'CategoryController');

Route::get('/pegawai', 'PegawaiController@index');

Auth::routes();
Route::match(["GET", "POST"], "/register", function(){
	return redirect("/login");
})->name("register");

Route::get('/home', 'HomeController@index')->name('home');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    public function user(){
		return $this->belongsTo('App\User');
	}
	
	public function books(){
		return $this->belongsToMany('App\Book')->withPivot('quantity');;
	}
	
	public function getTotalQuantityAttribute(){
		$total_quantity = 0;
		foreach($this->books as $book){
			$total_quantity += $book->pivot->quantity;
		}
		return $total_quantity;
	}
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class OrderController extends Controller
{
	public function __construct(){
		$this->middleware(function($request, $next){
			if(Gate::allows('manage-orders')) return $next($request);
			abort(403, 'Anda tidak memiliki cukup hak akses');
		});
	}
	
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
		$status = $request->get('status');
		$buyer_email = $request->get('buyer_email');
		$orders = \App\Order::with('user')->with('books')->whereHas('user', function($query) use ($buyer_email) {
			$query->where('email', 'LIKE', "%$buyer_email%");
		})->where('status', 'LIKE', "%$status%")->paginate(10);
		return view('orders.index', ['orders' => $orders]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $order = \App\Order::findOrFail($id);
		return view('orders.edit', ['order' => $order]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $order = \App\Order::findOrFail($id);
		$order->status = $request->get('status');
		$order->save();
		return redirect()->route('orders.edit', [$order->id])->with('status', 'Order status succesfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/orders/create.blade.php
@extends('layouts.global')
@section('footer-scripts')
	<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
	<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
	<script>
		$('#categories').select2({
			ajax: {
				url: 'http://localhost/belajar_laravel/public/ajax/categories/search',
				processResults: function(data){
					return {
						results: data.map(function(item){return {id: item.id, text:
						item.name} })
					}
				}
			}
		});
	</script>
@endsection
@section('title') Create book @endsection
@section('content')
	@if(session('status'))
		<div class="alert alert-success">
		{{session('status')}}
		</div>
	@endif
	<div class="row">
		<div class="col-md-8">
			<form action="{{route('books.store')}}" method="POST" enctype="multipart/form-data" class="shadow-sm p-3 bg-white">
				@csrf
				<label for="title">Title</label> <br>
				<input type="text" class="form-control" name="title" placeholder="Book title">
				<br>
				<label for="cover">Cover</label>
				<input type="file" class="form-control" name="cover">
				<br>
				<label for="categories">Categories</label><br>
				<select name="categories[]" multiple id="categories" class="form-control"> </select>
				<br><br/>
				<label for="description">Description</label><br>
				<textarea name="description" id="description" class="formcontrol" placeholder="Give a description about this book"></textarea>
				<br>
				<label for="stock">Stock</label><br>
				<input type="number" class="form-control" id="stock" name="stock" min="0" value="0">
				<br>
				<label for="author">Author</label><br>
				<input type="text" class="form-control" name="author" id="author" placeholder="Book author">
				<br>
				<label for="publisher">Publisher</label> <br>
				<input type="text" class="form-control" id="publisher" name="publisher" placeholder="Book publisher">
				<br>
				<label for="Price">Price</label> <br>
				<input type="number" class="form-control" name="price" id="price" placeholder="Book price">
				<br>
				<button class="btn btn-primary" name="save_action" value="PUBLISH">Publish</button>
				<button class="btn btn-secondary" name="save_action" value="DRAFT">Save as draft</button>
			</form>
		</div>
	</div>
@endsection

resources/views/orders/edit.blade.php
@extends('layouts.global')
@section('title') Edit order @endsection
@section('content')
<div class="row">
	<div class="col-md-8">
		@if(session('status'))
			<div class="alert alert-success">
				{{session('status')}}
			</div>
		@endif
		<form class="shadow-sm bg-white p-3" action="{{route('orders.update', [$order->id])}}" method="POST">
			@csrf
			<input type="hidden" name="_method" value="PUT">
			<label for="invoice_number">Invoice number</label><br>
			<input type="text" class="form-control" value="{{$order->invoice_number}}" disabled>
			<br>
			<label for="">Buyer</label><br>
			<input disabled class="form-control" type="text" value="{{$order->user->name}}">
			<br>
			<label for="created_at">Order date</label><br>
			<input type="text" class="form-control" value="{{$order->created_at}}" disabled >
			<br>
			<label for="">Books ({{$order->totalQuantity}}) </label><br>
			<ul>
				@foreach($order->books as $book)
					<li>{{$book->title}} <b>({{$book->pivot->quantity}})</b></li>
				@endforeach
			</ul>
			<label for="">Total price</label><br>
			<input class="form-control" type="text" value="{{$order->total_price}}" disabled>
			<br>
			<label for="status">Status</label><br>
			<select class="form-control" name="status" id="status">
				<option {{$order->status == "SUBMIT" ? "selected" : ""}}value="SUBMIT">SUBMIT</option>
				<option {{$order->status == "PROCESS" ? "selected" : ""}}value="PROCESS">PROCESS</option>
				<option {{$order->status == "FINISH" ? "selected" : ""}}value="FINISH">FINISH</option>
				<option {{$order->status == "CANCEL" ? "selected" : ""}}value="CANCEL">CANCEL</option>
			</select>
			<br>
			<input type="submit" class="btn btn-primary" value="Update">
		</form>
	</div>
</div>
@endsection

resources/views/orders/index.blade.php
@extends('layouts.global')
@section('title') Orders list @endsection
@section('content')
<form action="{{route('orders.index')}}">
	<div class="row">
		<div class="col-md-5">
			<input value="{{Request::get('buyer_email')}}" name="buyer_email" type="text" class="form-control" placeholder="Search by buyer email">
		</div>
		<div class="col-md-2">
			<select name="status" class="form-control" id="status">
				<option value="">ANY</option>
				<option {{Request::get('status') == "SUBMIT" ? "selected" : ""}} value="SUBMIT">SUBMIT</option>
				<option {{Request::get('status') == "PROCESS" ? "selected" : ""}} value="PROCESS">PROCESS</option>
				<option {{Request::get('status') == "FINISH" ? "selected" : ""}} value="FINISH">FINISH</option>
				<option {{Request::get('status') == "CANCEL" ? "selected" : ""}} value="CANCEL">CANCEL</option>
			</select>
		</div>
		<div class="col-md-2">
			<input type="submit" value="Filter" class="btn btn-primary">
		</div>
	</div>
</form>
<hr class="my-3">

<div class="row">
	<div class="col-md-12">
		<table class="table table-stripped table-bordered">
			<thead>
				<tr>
					<th>Invoice number</th>
					<th><b>Status</b></th>
					<th><b>Buyer</b></th>
					<th><b>Total quantity</b></th>
					<th><b>Order date</b></th>
					<th><b>Total price</b></th>
					<th><b>Actions</b></th>
				</tr>
			</thead>
			<tbody>
				@foreach($orders as $order)
					<tr>
						<td>{{$order->invoice_number}}</td>
						<td>
							@if($order->status == "SUBMIT")
								<span class="badge bg-warning text-light">{{$order->status}}</span>
							@elseif($order->status == "PROCESS")
								<span class="badge bg-info text-light">{{$order->status}}</span>
							@elseif($order->status == "FINISH")
								<span class="badge bg-success text-light">{{$order->status}}</span>
							@elseif($order->status == "CANCEL")
								<span class="badge bg-dark text-light">{{$order->status}}</span>
							@endif
						</td>
						<td>
							{{$order->user->name}} <br>
							<small>{{$order->user->email}}</small>
						</td>
						<td>{{$order->totalQuantity}} pc (s)</td>
						<td>{{$order->created_at}}</td>
						<td>{{$order->total_price}}</td>
						<td>
							<a href="{{route('orders.edit', [$order->id])}}" class="btn btn-info btnsm"> Edit</a>
						</td>
					</tr>
				@endforeach
			</tbody>
			<tfoot>
				<tr>
					<td colspan="10">
						{{$orders->appends(Request::all())->links()}}
					</td>
				</tr>
			</tfoot>
		</table>
	</div>
</div>
@endsection

resources/views/orders/show.blade.php
@extends('layouts.global')
@section('title') Detail Category @endsection
@section('content')
<div class="col-md-8">
	<div class="card">
		<div class="card-body">
			<label><b>Category name</b></label><br>
			{{$category->name}}
			<br><br>
			<label><b>Category slug</b></label><br>
			{{$category->slug}}
			<br><br>
			<label><b>Category image</b></label><br>
			@if($category->image)
			<img src="{{asset('storage/' . $category->image)}}" width="120px">
			@endif
		</div>
	</div>
</div>
@endsection

resources/views/orders/trash.blade.php
@extends('layouts.global')
@section('title') Trashed Books @endsection
@section('content')

<div class="row">
	<div class="col-md-6">
		<form action="{{route('books.index')}}" >
			<div class="input-group">
				<input name="keyword" type="text" value="{{Request::get('keyword')}}" class="form-control" placeholder="Filter by title">
				<div class="input-group-append">
					<input type="submit" value="Filter" class="btn btn-primary">
				</div>
			</div>
		</form>
	</div>
	<div class="col-md-6">
		<ul class="nav nav-pills card-header-pills">
			<li class="nav-item">
				<a class="nav-link {{Request::get('status') == NULL && Request::path() == 'books' ? 'active' : ''}}" href="{{route('books.index')}}">All</a>
			</li>
			<li class="nav-item">
				<a class="nav-link {{Request::get('status') == 'publish' ? 'active' : '' }}" href="{{route('books.index', ['status' => 'publish'])}}">Publish</a>
			</li>
			<li class="nav-item">
				<a class="nav-link {{Request::get('status') == 'draft' ? 'active' : '' }}" href="{{route('books.index', ['status' => 'draft'])}}">Draft</a>
			</li>
			<li class="nav-item">
				<a class="nav-link {{Request::path() == 'books/trash' ? 'active' : ''}}" href="{{route('books.trash')}}">Trash</a>
			</li>
		</ul>
	</div>
</div>
<hr class="my-3">
<div class="row">
	<div class="col-md-12">
		@if(session('status'))
			<div class="alert alert-success">
				{{session('status')}}
			</div>
		@endif
		<table class="table table-bordered table-stripped">
			<thead>
				<tr>
					<th><b>Cover</b></th>
					<th><b>Title</b></th>
					<th><b>Author</b></th>
					<th><b>Categories</b></th>
					<th><b>Stock</b></th>
					<th><b>Price</b></th>
					<th><b>Action</b></th>
				</tr>
			</thead>
			<tbody>
				@foreach($books as $book)
					<tr>
						<td>
							@if($book->cover)
								<img src="{{asset('storage/' . $book->cover)}}" width="96px"/>
							@endif
						</td>
						<td>{{$book->title}}</td>
						<td>{{$book->author}}</td>
						<td>
							<ul class="pl-3">
								@foreach($book->categories as $category)
									<li>{{$category->name}}</li>
								@endforeach
							</ul>
						</td>
						<td>{{$book->stock}}</td>
						<td>{{$book->price}}</td>
						<td>
							<form method="POST" action="{{route('books.restore', [$book->id])}}" class="d-inline">
								@csrf
								<input type="submit" value="Restore" class="btn btn-success"/>
							</form>
							<form method="POST" action="{{route('books.delete-permanent', [$book->id])}}" class="d-inline" 
								onsubmit="return confirm('Delete this book permanently?')">
								@csrf
								<input type="hidden" name="_method" value="DELETE">
								<input type="submit" value="Delete" class="btn btn-danger btn-sm">
							</form>
						</td>
					</tr>
				@endforeach
			</tbody>
			<tfoot>
				<tr>
					<td colspan="10">
						{{$books->appends(Request::all())->links()}}
					</td>
				</tr>
			</tfoot>
		</table>
	</div>
</div>
@endsection